/**
 * Adversarial decode cases, from the shared vector file and from specific defects.
 *
 * `test-vectors/adversarial-vectors.json` is generated by
 * `scripts/gen_adversarial_vectors.py` and read by both test suites, so the two
 * implementations are held to one accepted language. The tests below it pin
 * individual defects that corpus found.
 */
import assert from "node:assert/strict"
import test from "node:test"
import { readFileSync } from "node:fs"
import { fileURLToPath } from "node:url"
import {
  DEFAULT_DECODE_LIMITS,
  UNLIMITED_DECODE_LIMITS,
  decodeToken,
  encodeSpectrum,
  SpectrlDecodeError,
} from "../src/index.ts"
import { b64urlDecode, b64urlEncode } from "../src/base64url.ts"
import { tokenChecksum } from "../src/checksum.ts"
import { readTokenDocument } from "../src/cbor_format.ts"

interface Vector { name: string; rule: string; expect: "accept" | "reject"; token: string }
const vectors: Vector[] = JSON.parse(
  readFileSync(fileURLToPath(new URL("../../test-vectors/adversarial-vectors.json", import.meta.url)), "utf8"),
).vectors

function frameText(payload: string, mode = "r"): string {
  const body = `spectrl.v3.${mode}.${payload}`
  return `${body}.${tokenChecksum(body)}`
}

test("shared adversarial vectors get the verdict the specification requires", () => {
  const wrong: string[] = []
  for (const v of vectors) {
    let accepted: boolean
    try {
      decodeToken(v.token)
      accepted = true
    } catch (e) {
      accepted = false
      // The only exception a malformed token may produce is the decode error.
      if (!(e instanceof SpectrlDecodeError)) {
        wrong.push(`${v.name}: raised ${(e as Error)?.constructor?.name} instead of SpectrlDecodeError`)
        continue
      }
    }
    if (accepted !== (v.expect === "accept")) wrong.push(`${v.name}: expected ${v.expect} by rule '${v.rule}'`)
  }
  assert.deepEqual(wrong, [], `${wrong.length} of ${vectors.length} vectors disagree`)
})

test("the vector file covers every specification section", () => {
  const sections = new Set(vectors.map(v => v.rule.split(" ")[0]))
  for (const section of ["1", "2", "3", "4", "5", "7", "8"]) assert.ok(sections.has(section), `section ${section} uncovered`)
})

// --- section 1: one token string per payload ---------------------------------

const token = () => encodeSpectrum(
  { defaultArrayLength: 3, mz: [100, 200, 300], intensity: [1, 2, 3] },
  { lossless: true, compression: "raw" },
)

test("a payload has exactly one valid token string", () => {
  const original = token()
  const payload = original.split(".")[3]!
  const last = payload[payload.length - 1]!
  for (const alias of [payload + "=", payload + "==", payload + "===",
    payload.slice(0, -1) + String.fromCharCode(last.charCodeAt(0) + 1)]) {
    assert.throws(() => decodeToken(frameText(alias)), SpectrlDecodeError, `alias accepted: ${alias.slice(-8)}`)
  }
  assert.ok(decodeToken(original))
})

test("base64url trailing bits must be zero", () => {
  assert.deepEqual(Array.from(b64urlDecode("_-4")), [0xff, 0xee])
  for (const alias of ["_-5", "_-6", "_-7"]) assert.throws(() => b64urlDecode(alias), /trailing bits/)
})

test("integral values must be CBOR integers, not floats", () => {
  // JavaScript cannot tell 3 from 3.0 after parsing, so the wire form is what
  // distinguishes them and the float spelling has to be refused outright.
  const raws: number[][] = [
    [0xa2, 0x00, 0xfb, 0x40, 0x08, 0, 0, 0, 0, 0, 0, 0x06, 0x80], // 3.0 float64
    [0xa2, 0x00, 0xfa, 0x40, 0x40, 0, 0, 0x06, 0x80], // 3.0 float32
    [0xa2, 0x00, 0xf9, 0x42, 0x00, 0x06, 0x80], // 3.0 float16
    [0xa2, 0x00, 0xfb, 0x80, 0, 0, 0, 0, 0, 0, 0, 0x06, 0x80], // -0.0
  ]
  for (const raw of raws) {
    assert.throws(() => decodeToken(frameText(b64urlEncode(Uint8Array.from(raw)))), /must be CBOR integers/)
  }
})

// --- section 8: resource budgets ---------------------------------------------

const amplification = vectors.find(v => v.name === "limits/decode_amplification")!.token

test("decode amplification is refused by the default budgets", () => {
  // ~21 kB of token, 128 MB of float64 if it were decoded.
  assert.ok(amplification.length < 32 * 1024)
  assert.throws(() => decodeToken(amplification), /maxPeaks|maxDecodedBytes/)
  assert.throws(() => decodeToken(amplification, {}), /maxPeaks|maxDecodedBytes/)
})

test("budgets apply to inspection too", () => {
  assert.throws(() => readTokenDocument(amplification), SpectrlDecodeError)
})

test("default budgets clear the largest corpus spectrum with room to spare", () => {
  // 217,009 peaks in a 1.05 MB token is the largest real case measured.
  assert.ok(DEFAULT_DECODE_LIMITS.maxPeaks >= 217_009 * 4)
  assert.ok(DEFAULT_DECODE_LIMITS.maxTokenBytes >= 1_048_822 * 3)
  const worstOutput = DEFAULT_DECODE_LIMITS.maxPeaks * 8 * DEFAULT_DECODE_LIMITS.maxArrays
  assert.ok(worstOutput / DEFAULT_DECODE_LIMITS.maxTokenBytes <= 128)
})

test("unlimited is available for a trusted producer", () => {
  const n = 1_200_000
  const mz = new Float64Array(n)
  for (let i = 0; i < n; i++) mz[i] = 100 + i / 1000
  const big = encodeSpectrum({ defaultArrayLength: n, mz }, { lossless: true })
  assert.throws(() => decodeToken(big), /maxPeaks/)
  assert.equal(decodeToken(big, UNLIMITED_DECODE_LIMITS).defaultArrayLength, n)
})

test("encoding is not bound by the decode budgets", () => {
  const n = 1_200_000
  const mz = new Float64Array(n)
  for (let i = 0; i < n; i++) mz[i] = 100 + i / 1000
  assert.ok(encodeSpectrum({ defaultArrayLength: n, mz }, { lossless: true }))
})
