from pathlib import Path
import pprint
import numpy as np
from spectrl import InlineSpectrum, encode_spectrum, decode_token
from spectrl.model import SpectrlCvParam
from spectrl.cbor_format import read_token_document
s = InlineSpectrum(3, id='scan=42', mz=np.array([100.,101.,102.]), intensity=np.array([5,10,2], dtype='float32'),
    params=[SpectrlCvParam('MS:1000511', 2)], source={'name':'example.mzML'},
    acquisition={'instrument':{'name':'Example instrument'}},
    processing=[{'software':{'name':'Example converter','version':'1.0'}}])
t = encode_spectrum(s, lossless=True, array_encodings={'mz': 'modular-delta-shuffle', 'intensity': 'byte-shuffle'})
doc,_=read_token_document(t)
assert decode_token(t).mz.tobytes()==s.mz.tobytes()
text='''# Implemented v3 payload example

This example is generated by `scripts/gen_payload_example.py` and verified with
the local v3 decoder. The exact wire contract is in [SPECIFICATION.md](../SPECIFICATION.md).

The spectrum has three float64 m/z values (100, 101, 102), float32 intensities
(5, 10, 2), an MS level, and optional source, instrument, and software context.
The names are illustrative. This lossless example uses modular delta plus byte
shuffle for m/z and byte shuffle for intensity, followed by whole-document zlib.

```text
TOKEN
```

The default mode after `v3` is `z` for whole-document zlib. Other modes are
`r` for raw CBOR and `b` for Brotli. All use base64url.
Only explicit `auto` selects the smallest complete token.

The decoded CBOR document below uses actual integer keys and operation tuples.
Python byte literals show the exact numeric encoding blobs.

```python
DOCUMENT
```

Top-level key 6 holds the arrays. Descriptor key 0 gives dtype, key 1 gives
array identity, key 2 gives encoding, key 5 holds bytes, and key 7 gives
fidelity (0 means exact for the supplied values). `[2, 1]` selects modular delta
plus shuffle at revision 1. `[1, 1]` selects byte shuffle at revision 1.
Descriptor key 3 is invalid. Compression is declared only by the token mode.

Custom identifiers use the same tuples, for example
`["org.example:predictor", 1, {"window": 4}]`. Applications register implementations
explicitly. Token content never downloads or executes a codec.

CV parameters are ordered pairs, so repeated accessions survive. Keys 8, 9,
and 10 hold source, acquisition, and processing context. Optional namespaced
extensions use key 11. Unknown optional extensions survive forwarding.
Unknown required extensions permit inspection but prevent full decoding.

The trailing eight hexadecimal characters are CRC32 over the ASCII prefix
and mode and payload, including their dots. They detect accidental corruption. There
is no built-in spectrum identifier or decoded-data hash.

Peak selection appends a `spectrl:peak-selection` processing record with
`method`, `inputPeakCount`, and `outputPeakCount` parameters. A lossy decode
appends per-array `spectrl:lossy-encoding` history. Later exact recompression
preserves this history. Exact current encoding does not imply an unmodified
original acquisition.
'''.replace('TOKEN',t).replace('DOCUMENT',pprint.pformat(doc, width=90, sort_dicts=True))
Path('docs/v3-payload-example.md').write_text(text)
